### ISSUE TITLE
Company mode support?

### ISSUE THREAD

**Issue by failable** [habamax/wildcharm-theme#3]
Thanks for the wonderful theme. I find that currently support for `company` is missing. Can please you add support for it?

**Comment by habamax** [comment]
Sure!

**Comment by habamax** [comment]
Could you try latest (I don't use company so tested only basic things)

**Comment by failable** [comment]
Thanks for your work! It looks pretty much the same as `corfu` now.


Company:
<img width="562" alt="Screenshot 2023-09-09 at 16 11 17" src="https://github.com/habamax/wildcharm-theme/assets/5475262/c304ae12-68c3-498f-ba64-3d4d83fa03ad">



Corfu:
<img width="143" alt="Screenshot 2023-09-09 at 16 08 13" src="https://github.com/habamax/wildcharm-theme/assets/5475262/47e1d885-a6e1-4caa-82fb-bfddf59464c4">

**Comment by habamax** [comment]
I would change `(Function) 1` color, do you know what is this?

**Comment by failable** [comment]
Maybe it's https://github.com/company-mode/company-mode/blob/7c24dc8668af5aea8a5d07aeceda5fac7a2a85b5/company.el#L123 ?

**Comment by habamax** [comment]
Could you pls check it?

**Comment by failable** [comment]
Checked!
<img width="477" alt="Screenshot 2023-09-09 at 16 51 49" src="https://github.com/habamax/wildcharm-theme/assets/5475262/48d1a5f6-74c1-4711-99b9-129d2e86b7f5">

**Comment by habamax** [comment]
Great, thank you!
