### ISSUE TITLE
Support for `iedit`

### ISSUE THREAD

**Issue by failable** [habamax/wildcharm-theme#4]
Since both `iedit-occurrence` and `lsp-face-highlight-textual` both inherit from `highlight`, when doing `iedit-mode` under a LSP highlighted symbol, the faces are indistinguishable which means that it's hard to make sure if `iedit` is successfully enabled (though the modeline contains indicator for that).

LSP highlighted:
<img width="442" alt="Screenshot 2023-09-09 at 16 30 03" src="https://github.com/habamax/wildcharm-theme/assets/5475262/8dafa423-88bd-4271-8c29-f5be0de0d9f0">

Note `iedit` is enabled in this case
<img width="550" alt="Screenshot 2023-09-09 at 16 30 11" src="https://github.com/habamax/wildcharm-theme/assets/5475262/3eeba036-b0c4-4c55-9ac2-3f9a8b43fe37">

**Comment by habamax** [comment]
I don't use `lsp-mode`, but for eglot I have defined `eglot-highlight-symbol-face`. Let me add the same for lsp-mode, and I will rely on you to check it :)

**Comment by habamax** [comment]
could you please check?

**Comment by failable** [comment]
Looks good! Thanks!
<img width="453" alt="Screenshot 2023-09-09 at 16 43 57" src="https://github.com/habamax/wildcharm-theme/assets/5475262/7b95fc32-d93e-476d-aed5-be62063e9df1">
